import img1 from '../MyAssets/Premium Cotton T-Shirt.png';
import img2 from '../MyAssets/Slim Fit Jeans.png';
import img3 from '../MyAssets/Floral Summer Dress.png';
import img4 from '../MyAssets/Kids Hoodie.png';
import img5 from '../MyAssets/Running Shoes.png';
import img6 from '../MyAssets/Denim Jacket.png';
import img7 from '../MyAssets/Cartoon T-Shirt.png';
import img8 from '../MyAssets/Formal Shirt.png';
import img9 from '../MyAssets/Yoga Pants.png';
import img10 from '../MyAssets/Winter Coat.png';
import img11 from '../MyAssets/Graphic Tee.png';
import img12 from '../MyAssets/Kids Sneakers.png';
import img13 from '../MyAssets/Leather Wallet.png';
import img14 from '../MyAssets/Summer Shorts.png';
import img15 from '../MyAssets/Kids Backpack.png';
import img16 from '../MyAssets/Blazer.png';
import img17 from '../MyAssets/Maxi Dress.png';
import img18 from '../MyAssets/Kids Winter Jacket.png';
import img19 from '../MyAssets/Cargo Pants.png';
import img20 from '../MyAssets/Silk Scarf.png';
import img21 from '../MyAssets/Baseball Cap.png';
import img22 from '../MyAssets/Swimwear Set.png';
import img23 from '../MyAssets/Kids Jeans.png';
import img24 from '../MyAssets/Dress Shoes.png';
import img25 from '../MyAssets/Crossbody Bag.png';
import img26 from '../MyAssets/Kids Rain Boots.png';
import img27 from '../MyAssets/Hooded Sweatshirt.png';
import img28 from '../MyAssets/Wool Coat.png';
import img29 from '../MyAssets/Kids Pajama Set.png';
import img30 from '../MyAssets/Leather Belt.png';
import img31 from '../MyAssets/Wrap Dress.png';
import img32 from '../MyAssets/Kids Sneakers.png';
import img33 from '../MyAssets/Polo Shirt.png';
import img34 from '../MyAssets/Knit Sweater.png';
import img35 from '../MyAssets/Kids Winter Hat.png';
import img36 from '../MyAssets/Chino Pants.png';
import img37 from '../MyAssets/Silk Blouse.png';
import img38 from '../MyAssets/Kids Backpack1.png';
import img39 from '../MyAssets/Denim Shirt.png';
import img40 from '../MyAssets/Midi Skirt.png';
import img41 from '../MyAssets/Kids Swim Trunks.png';
import img42 from '../MyAssets/Winter Gloves.png';
import img43 from '../MyAssets/Turtleneck Sweater.png';
import img44 from '../MyAssets/Kids Leggings.png';
import img45 from '../MyAssets/Bomber Jacket.png';
import img46 from '../MyAssets/Linen Pants.png';
import img47 from '../MyAssets/Kids Winter Gloves.png';
import img48 from '../MyAssets/Dress Shirt.png';
import img49 from '../MyAssets/Wool Scarf.png';
import img50 from '../MyAssets/Kids Hoodie1.png';
import img51 from '../MyAssets/Leather Jacket.png';
import img52 from '../MyAssets/Cashmere Sweater.png';


let AllProducts = [
    {
      id: 1,
      title: "Premium Cotton T-Shirt",
      category: "men",
      oldPrice: 34.99,
      newPrice: 29.99,
      discount: 15,
      rating: 4.5,
      popularWith: ["men"],
      image: img1,
      colors: ["white", "black", "navy"],
      sizes: ["S", "M", "L", "XL"],
      description: "Soft premium cotton t-shirt with comfortable fit",
      stock: 45,
      tags: ["best seller", "summer"]
    },
    {
      id: 2,
      title: "Slim Fit Jeans",
      category: "men",
      oldPrice: 74.99,
      newPrice: 59.99,
      discount: 20,
      rating: 4.7,
      popularWith: ["men"],
      image: img2,
      colors: ["blue", "black"],
      sizes: ["28", "30", "32", "34"],
      description: "Modern slim fit jeans with stretch technology",
      stock: 32,
      tags: ["trending"]
    },
    {
      id: 3,
      title: "Floral Summer Dress",
      category: "women",
      oldPrice: 69.99,
      newPrice: 49.99,
      discount: 30,
      rating: 4.8,
      popularWith: ["women"],
      image: img3,
      colors: ["red", "yellow", "blue"],
      sizes: ["S", "M", "L"],
      description: "Lightweight floral dress perfect for summer",
      stock: 28,
      tags: ["best seller", "summer"]
    },
    {
      id: 4,
      title: "Kids Hoodie",
      category: "kids",
      oldPrice: 39.99,
      newPrice: 24.99,
      discount: 40,
      rating: 4.6,
      popularWith: ["kids"],
      image: img4,
      colors: ["pink", "blue", "gray"],
      sizes: ["4-5Y", "6-7Y", "8-9Y"],
      description: "Cozy hoodie with fun prints for kids",
      stock: 51,
      tags: ["winter"]
    },
    {
      id: 5,
      title: "Running Shoes",
      category: "men",
      oldPrice: 119.99,
      newPrice: 89.99,
      discount: 25,
      rating: 4.9,
      popularWith: ["men", "women"],
      image: img5,
      colors: ["black", "white", "red"],
      sizes: ["8", "9", "10", "11"],
      description: "High-performance running shoes with cushioning",
      stock: 24,
      tags: ["best seller", "sports"]
    },
    {
      id: 6,
      title: "Denim Jacket",
      category: "women",
      oldPrice: 79.99,
      newPrice: 69.99,
      discount: 15,
      rating: 4.4,
      image: img6,
      colors: ["blue", "black"],
      sizes: ["S", "M", "L"],
      description: "Classic denim jacket with modern fit",
      stock: 18,
      tags: ["spring"]
    },
    {
      id: 7,
      title: "Cartoon T-Shirt",
      category: "kids",
      oldPrice: 29.99,
      newPrice: 14.99,
      discount: 50,
      rating: 4.7,
      popularWith: ["kids"],
      image: img7,
      colors: ["white", "yellow"],
      sizes: ["2-3Y", "4-5Y", "6-7Y"],
      description: "Fun cartoon print t-shirt for kids",
      stock: 63,
      tags: ["summer", "best seller"]
    },
    {
      id: 8,
      title: "Formal Shirt",
      category: "men",
      oldPrice: 44.99,
      newPrice: 39.99,
      discount: 10,
      rating: 4.3,
      image: img8,
      colors: ["white", "blue"],
      sizes: ["S", "M", "L", "XL"],
      description: "Classic formal shirt for office wear",
      stock: 37,
      tags: ["office"]
    },
    {
      id: 9,
      title: "Yoga Pants",
      category: "women",
      oldPrice: 54.99,
      newPrice: 39.99,
      discount: 28,
      rating: 4.6,
      popularWith: ["women"],
      image: img9,
      colors: ["black", "gray", "burgundy"],
      sizes: ["XS", "S", "M", "L"],
      description: "High-waisted yoga pants with moisture-wicking fabric",
      stock: 42,
      tags: ["fitness", "best seller"]
    },
    {
      id: 10,
      title: "Winter Coat",
      category: "women",
      oldPrice: 149.99,
      newPrice: 119.99,
      discount: 20,
      rating: 4.8,
      popularWith: ["women"],
      image: img10,
      colors: ["black", "camel", "navy"],
      sizes: ["S", "M", "L"],
      description: "Warm winter coat with faux fur trim",
      stock: 15,
      tags: ["winter", "premium"]
    },
    {
      id: 11,
      title: "Graphic Tee",
      category: "men",
      oldPrice: 29.99,
      newPrice: 19.99,
      discount: 33,
      rating: 4.2,
      image: img11,
      colors: ["white", "black", "red"],
      sizes: ["S", "M", "L", "XL"],
      description: "Casual graphic t-shirt with urban design",
      stock: 56,
      tags: ["casual"]
    },
    {
      id: 12,
      title: "Kids Sneakers",
      category: "kids",
      oldPrice: 49.99,
      newPrice: 34.99,
      discount: 30,
      rating: 4.5,
      popularWith: ["kids"],
      image: img12,
      colors: ["blue", "pink", "black"],
      sizes: ["10C", "12C", "1Y", "2Y"],
      description: "Comfortable sneakers for active kids",
      stock: 38,
      tags: ["school", "best seller"]
    },
    {
      id: 13,
      title: "Leather Wallet",
      category: "men",
      oldPrice: 59.99,
      newPrice: 39.99,
      discount: 33,
      rating: 4.4,
      image: img13,
      colors: ["brown", "black"],
      description: "Genuine leather bifold wallet",
      stock: 27,
      tags: ["accessories"]
    },
    {
      id: 14,
      title: "Summer Shorts",
      category: "women",
      oldPrice: 39.99,
      newPrice: 29.99,
      discount: 25,
      rating: 4.3,
      popularWith: ["women"],
      image: img14,
      colors: ["denim", "white", "khaki"],
      sizes: ["XS", "S", "M", "L"],
      description: "Comfortable denim shorts for summer",
      stock: 49,
      tags: ["summer"]
    },
    {
      id: 15,
      title: "Kids Backpack",
      category: "kids",
      oldPrice: 34.99,
      newPrice: 24.99,
      discount: 29,
      rating: 4.7,
      popularWith: ["kids"],
      image: img15,
      colors: ["blue", "pink", "green"],
      description: "Durable backpack with cartoon characters",
      stock: 62,
      tags: ["school", "best seller"]
    },
    {
      id: 16,
      title: "Blazer",
      category: "men",
      oldPrice: 129.99,
      newPrice: 99.99,
      discount: 23,
      rating: 4.6,
      image: img16,
      colors: ["navy", "black", "gray"],
      sizes: ["S", "M", "L", "XL"],
      description: "Slim fit blazer for formal occasions",
      stock: 14,
      tags: ["office", "premium"]
    },
    {
      id: 17,
      title: "Maxi Dress",
      category: "women",
      oldPrice: 79.99,
      newPrice: 59.99,
      discount: 25,
      rating: 4.8,
      popularWith: ["women"],
      image: img17,
      colors: ["black", "red", "floral"],
      sizes: ["S", "M", "L"],
      description: "Elegant maxi dress for special occasions",
      stock: 21,
      tags: ["evening", "best seller"]
    },
    {
      id: 18,
      title: "Kids Winter Jacket",
      category: "kids",
      oldPrice: 69.99,
      newPrice: 49.99,
      discount: 29,
      rating: 4.5,
      popularWith: ["kids"],
      image: img18,
      colors: ["red", "blue", "pink"],
      sizes: ["2-3Y", "4-5Y", "6-7Y"],
      description: "Warm winter jacket with waterproof exterior",
      stock: 33,
      tags: ["winter"]
    },
    {
      id: 19,
      title: "Cargo Pants",
      category: "men",
      oldPrice: 59.99,
      newPrice: 44.99,
      discount: 25,
      rating: 4.3,
      image: img19,
      colors: ["khaki", "black", "olive"],
      sizes: ["S", "M", "L", "XL"],
      description: "Durable cargo pants with multiple pockets",
      stock: 29,
      tags: ["casual"]
    },
    {
      id: 20,
      title: "Silk Scarf",
      category: "women",
      oldPrice: 49.99,
      newPrice: 34.99,
      discount: 30,
      rating: 4.4,
      image: img20,
      colors: ["blue", "red", "green", "floral"],
      description: "Luxury silk scarf with elegant print",
      stock: 47,
      tags: ["accessories"]
    },
    {
      id: 21,
      title: "Baseball Cap",
      category: "men",
      oldPrice: 24.99,
      newPrice: 19.99,
      discount: 20,
      rating: 4.1,
      image: img21,
      colors: ["black", "navy", "red"],
      description: "Adjustable baseball cap with logo",
      stock: 58,
      tags: ["casual"]
    },
    {
      id: 22,
      title: "Swimwear Set",
      category: "women",
      oldPrice: 59.99,
      newPrice: 39.99,
      discount: 33,
      rating: 4.6,
      popularWith: ["women"],
      image: img22,
      colors: ["black", "blue", "red"],
      sizes: ["XS", "S", "M", "L"],
      description: "Two-piece swimwear set with matching cover-up",
      stock: 26,
      tags: ["summer", "beach"]
    },
    {
      id: 23,
      title: "Kids Jeans",
      category: "kids",
      oldPrice: 34.99,
      newPrice: 24.99,
      discount: 29,
      rating: 4.3,
      image: img23,
      colors: ["blue", "black"],
      sizes: ["4-5Y", "6-7Y", "8-9Y"],
      description: "Durable jeans with reinforced knees",
      stock: 41,
      tags: ["school"]
    },
    {
      id: 24,
      title: "Dress Shoes",
      category: "men",
      oldPrice: 99.99,
      newPrice: 79.99,
      discount: 20,
      rating: 4.5,
      image: img24,
      colors: ["black", "brown"],
      sizes: ["8", "9", "10", "11"],
      description: "Classic oxford dress shoes",
      stock: 19,
      tags: ["formal"]
    },
    {
      id: 25,
      title: "Crossbody Bag",
      category: "women",
      oldPrice: 69.99,
      newPrice: 49.99,
      discount: 29,
      rating: 4.7,
      popularWith: ["women"],
      image: img25,
      colors: ["black", "tan", "red"],
      description: "Compact crossbody bag with multiple compartments",
      stock: 34,
      tags: ["accessories", "best seller"]
    },
    {
      id: 26,
      title: "Kids Rain Boots",
      category: "kids",
      oldPrice: 39.99,
      newPrice: 29.99,
      discount: 25,
      rating: 4.2,
      image: img26,
      colors: ["yellow", "blue", "pink"],
      sizes: ["10C", "12C", "1Y", "2Y"],
      description: "Waterproof rain boots with fun prints",
      stock: 53,
      tags: ["rain", "spring"]
    },
    {
      id: 27,
      title: "Hooded Sweatshirt",
      category: "men",
      oldPrice: 49.99,
      newPrice: 34.99,
      discount: 30,
      rating: 4.4,
      image: img27,
      colors: ["gray", "black", "navy"],
      sizes: ["S", "M", "L", "XL"],
      description: "Comfortable hooded sweatshirt with front pocket",
      stock: 37,
      tags: ["casual"]
    },
    {
      id: 28,
      title: "Wool Coat",
      category: "women",
      oldPrice: 199.99,
      newPrice: 149.99,
      discount: 25,
      rating: 4.9,
      popularWith: ["women"],
      image: img28,
      colors: ["black", "camel"],
      sizes: ["S", "M", "L"],
      description: "Premium wool coat with belt",
      stock: 12,
      tags: ["winter", "premium"]
    },
    {
      id: 29,
      title: "Kids Pajama Set",
      category: "kids",
      oldPrice: 29.99,
      newPrice: 19.99,
      discount: 33,
      rating: 4.6,
      popularWith: ["kids"],
      image: img29,
      colors: ["blue", "pink", "gray"],
      sizes: ["2-3Y", "4-5Y", "6-7Y"],
      description: "Soft cotton pajama set with fun prints",
      stock: 67,
      tags: ["sleepwear"]
    },
    {
      id: 30,
      title: "Leather Belt",
      category: "men",
      oldPrice: 39.99,
      newPrice: 29.99,
      discount: 25,
      rating: 4.3,
      image: img30,
      colors: ["black", "brown"],
      sizes: ["S", "M", "L", "XL"],
      description: "Genuine leather belt with metal buckle",
      stock: 43,
      tags: ["accessories"]
    },
    {
      id: 31,
      title: "Wrap Dress",
      category: "women",
      oldPrice: 69.99,
      newPrice: 49.99,
      discount: 29,
      rating: 4.8,
      popularWith: ["women"],
      image: img31,
      colors: ["black", "navy", "floral"],
      sizes: ["S", "M", "L"],
      description: "Flattering wrap dress for all occasions",
      stock: 25,
      tags: ["best seller"]
    },
    {
      id: 32,
      title: "Kids Sneakers",
      category: "kids",
      oldPrice: 44.99,
      newPrice: 34.99,
      discount: 22,
      rating: 4.4,
      image: img32,
      colors: ["white", "black", "pink"],
      sizes: ["10C", "12C", "1Y", "2Y"],
      description: "Lightweight sneakers with velcro straps",
      stock: 39,
      tags: ["school"]
    },
    {
      id: 33,
      title: "Polo Shirt",
      category: "men",
      oldPrice: 39.99,
      newPrice: 29.99,
      discount: 25,
      rating: 4.2,
      image: img33,
      colors: ["white", "black", "navy"],
      sizes: ["S", "M", "L", "XL"],
      description: "Classic polo shirt with breathable fabric",
      stock: 51,
      tags: ["casual"]
    },
    {
      id: 34,
      title: "Knit Sweater",
      category: "women",
      oldPrice: 59.99,
      newPrice: 44.99,
      discount: 25,
      rating: 4.7,
      popularWith: ["women"],
      image: img34,
      colors: ["cream", "gray", "pink"],
      sizes: ["S", "M", "L"],
      description: "Cozy knit sweater for cold days",
      stock: 31,
      tags: ["winter"]
    },
    {
      id: 35,
      title: "Kids Winter Hat",
      category: "kids",
      oldPrice: 19.99,
      newPrice: 14.99,
      discount: 25,
      rating: 4.3,
      image: img35,
      colors: ["blue", "pink", "red"],
      description: "Warm winter hat with fleece lining",
      stock: 72,
      tags: ["winter"]
    },
    {
      id: 36,
      title: "Chino Pants",
      category: "men",
      oldPrice: 54.99,
      newPrice: 39.99,
      discount: 27,
      rating: 4.5,
      image: img36,
      colors: ["khaki", "navy", "gray"],
      sizes: ["S", "M", "L", "XL"],
      description: "Versatile chino pants for casual wear",
      stock: 28,
      tags: ["casual"]
    },
    {
      id: 37,
      title: "Silk Blouse",
      category: "women",
      oldPrice: 79.99,
      newPrice: 59.99,
      discount: 25,
      rating: 4.6,
      popularWith: ["women"],
      image: img37,
      colors: ["white", "black", "blue"],
      sizes: ["S", "M", "L"],
      description: "Elegant silk blouse for office wear",
      stock: 22,
      tags: ["office"]
    },
    {
      id: 38,
      title: "Kids Backpack",
      category: "kids",
      oldPrice: 39.99,
      newPrice: 29.99,
      discount: 25,
      rating: 4.7,
      popularWith: ["kids"],
      image: img38,
      colors: ["blue", "pink", "black"],
      description: "Lightweight backpack with multiple pockets",
      stock: 59,
      tags: ["school", "best seller"]
    },
    {
      id: 39,
      title: "Denim Shirt",
      category: "men",
      oldPrice: 49.99,
      newPrice: 39.99,
      discount: 20,
      rating: 4.3,
      image: img39,
      colors: ["blue", "black"],
      sizes: ["S", "M", "L", "XL"],
      description: "Classic denim shirt with button-down collar",
      stock: 35,
      tags: ["casual"]
    },
    {
      id: 40,
      title: "Midi Skirt",
      category: "women",
      oldPrice: 49.99,
      newPrice: 34.99,
      discount: 30,
      rating: 4.5,
      image: img40,
      colors: ["black", "gray", "plaid"],
      sizes: ["S", "M", "L"],
      description: "Versatile midi skirt with elastic waist",
      stock: 41,
      tags: ["office"]
    },
    {
      id: 41,
      title: "Kids Swim Trunks",
      category: "kids",
      oldPrice: 24.99,
      newPrice: 19.99,
      discount: 20,
      rating: 4.2,
      image: img41,
      colors: ["blue", "red", "green"],
      sizes: ["4-5Y", "6-7Y"],
      description: "Quick-dry swim trunks with fun prints",
      stock: 47,
      tags: ["summer"]
    },
    {
      id: 42,
      title: "Winter Gloves",
      category: "men",
      oldPrice: 29.99,
      newPrice: 19.99,
      discount: 33,
      rating: 4.4,
      image: img42,
      colors: ["black", "brown", "gray"],
      description: "Warm winter gloves with touchscreen capability",
      stock: 38,
      tags: ["winter"]
    },
    {
      id: 43,
      title: "Turtleneck Sweater",
      category: "women",
      oldPrice: 64.99,
      newPrice: 49.99,
      discount: 23,
      rating: 4.7,
      popularWith: ["women"],
      image: img43,
      colors: ["black", "cream", "burgundy"],
      sizes: ["S", "M", "L"],
      description: "Warm turtleneck sweater for winter",
      stock: 27,
      tags: ["winter"]
    },
    {
      id: 44,
      title: "Kids Leggings",
      category: "kids",
      oldPrice: 19.99,
      newPrice: 14.99,
      discount: 25,
      rating: 4.3,
      image: img44,
      colors: ["black", "pink", "purple"],
      sizes: ["4-5Y", "6-7Y"],
      description: "Stretchy leggings with fun patterns",
      stock: 63,
      tags: ["school"]
    },
    {
      id: 45,
      title: "Bomber Jacket",
      category: "men",
      oldPrice: 89.99,
      newPrice: 69.99,
      discount: 22,
      rating: 4.6,
      image: img45,
      colors: ["black", "olive", "navy"],
      sizes: ["S", "M", "L", "XL"],
      description: "Stylish bomber jacket with ribbed trim",
      stock: 19,
      tags: ["casual"]
    },
    {
      id: 46,
      title: "Linen Pants",
      category: "women",
      oldPrice: 59.99,
      newPrice: 44.99,
      discount: 25,
      rating: 4.5,
      image: img46,
      colors: ["white", "beige", "black"],
      sizes: ["S", "M", "L"],
      description: "Breathable linen pants for summer",
      stock: 34,
      tags: ["summer"]
    },
    {
      id: 47,
      title: "Kids Winter Gloves",
      category: "kids",
      oldPrice: 19.99,
      newPrice: 14.99,
      discount: 25,
      rating: 4.2,
      image: img47,
      colors: ["blue", "pink", "red"],
      description: "Warm winter gloves with fun prints",
      stock: 57,
      tags: ["winter"]
    },
    {
      id: 48,
      title: "Dress Shirt",
      category: "men",
      oldPrice: 49.99,
      newPrice: 39.99,
      discount: 20,
      rating: 4.4,
      image: img48,
      colors: ["white", "blue"],
      sizes: ["S", "M", "L", "XL"],
      description: "Classic dress shirt with spread collar",
      stock: 31,
      tags: ["office"]
    },
    {
      id: 49,
      title: "Wool Scarf",
      category: "women",
      oldPrice: 39.99,
      newPrice: 29.99,
      discount: 25,
      rating: 4.3,
      image: img49,
      colors: ["gray", "burgundy", "navy"],
      description: "Warm wool scarf for cold weather",
      stock: 45,
      tags: ["winter"]
    },
    {
      id: 50,
      title: "Kids Hoodie",
      category: "kids",
      oldPrice: 34.99,
      newPrice: 24.99,
      discount: 29,
      rating: 4.6,
      popularWith: ["kids"],
      image: img50,
      colors: ["gray", "blue", "pink"],
      sizes: ["4-5Y", "6-7Y"],
      description: "Cozy hoodie with front pocket",
      stock: 52,
      tags: ["winter"]
    },
    {
      id: 51,
      title: "Leather Jacket",
      category: "men",
      oldPrice: 199.99,
      newPrice: 149.99,
      discount: 25,
      rating: 4.8,
      popularWith: ["men"],
      image: img51,
      colors: ["black", "brown"],
      sizes: ["S", "M", "L", "XL"],
      description: "Genuine leather motorcycle jacket",
      stock: 11,
      tags: ["premium"]
    },
    {
      id: 52,
      title: "Cashmere Sweater",
      category: "women",
      oldPrice: 149.99,
      newPrice: 119.99,
      discount: 20,
      rating: 4.9,
      popularWith: ["women"],
      image: img52,
      colors: ["cream", "gray", "pink"],
      sizes: ["S", "M", "L"],
      description: "Luxury cashmere sweater with ribbed trim",
      stock: 14,
      tags: ["premium", "winter"]
    }
  ];

export default AllProducts;